TutorsOfMogilev_NetCore/Controllers/API/TutorsController.cs
using Core.Models;
using Data.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Modules.TutorModule;
using Modules.TutorModule.Filters;
using System.Linq;
using System.Threading.Tasks;
using TutorsOfMogilev_NetCore.Models;
using TutorsOfMogilev_NetCore.Services;

namespace TutorsOfMogilev_NetCore.Controllers.API
{
#if !DEBUG
    [Authorize]
#endif
    [Route("api/[controller]")]
    public class TutorsController : Controller
    {
        private readonly TutorRepository _tutorRepository;
        private readonly ImageService _imageService;

        public TutorsController(TutorRepository tutorRepository, ImageService imageService)
        {
            _tutorRepository = tutorRepository;
            _imageService = imageService;
        }

        [HttpGet]
        public async Task<ListModel<TutorDTO>> Get([FromQuery] TutorListFilter filter)
        {
            return await _tutorRepository.GetList(filter);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Get(long id)
        {
            var result = await _tutorRepository.GetItem(id);

            if (result == null)
                return NotFound();

            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] TutorDTO item)
        {
            if (!ModelState.IsValid)
                throw new System.Exception(
                    ModelState.Values
                        .Select(x =>
                            x.Errors
                            .Select(y => y.ErrorMessage)
                                .Aggregate((a, b) => $"{a} \n {b}")
                            )
                        .Aggregate((a, b) => $"{a} \n {b}"));

            var result = await _tutorRepository.InsertItem(item);

            if (result == null)
                return BadRequest("Объект не был создан");

            return Ok(result);
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Put(int id, [FromBody] TutorDTO item)
        {
            item.Id = id;
            var result = await _tutorRepository.UpdateItem(item);

            if (result == null)
                return BadRequest("Объект не был обновлен");

            return Ok(result);
        }

        [HttpPut("{id}/subjects")]
        public async Task<IActionResult> UpdateTutorSubjects(int id, [FromBody] UpdateManytoManyModel data)
        {
            var result = await _tutorRepository.UpdateTutorSubjects(id, data.added, data.deleted);

            if (!result)
                return BadRequest("Объект не был обновлен");

            return Ok(result);
        }

        [HttpPut("{id}/specializations")]
        public async Task<IActionResult> UpdateTutorSpecializations(int id, [FromBody] UpdateManytoManyModel data)
        {
            var result = await _tutorRepository.UpdateTutorSpecializations(id, data.added, data.deleted);

            if (!result)
                return BadRequest("Объект не был обновлен");

            return Ok(result);
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var tutor = await _tutorRepository.GetItem(id);

            if (tutor != null && !string.IsNullOrWhiteSpace(tutor.PhotoPath))
            {
                _imageService.DeleteOldPhoto(tutor.PhotoPath);
            }

            var result = await _tutorRepository.DeleteItem(id);

            if (!result)
                return BadRequest("Объект не был удален");

            return Ok();
        }
    }
}

TutorsOfMogilev_NetCore/Controllers/MVC/ResumeController.cs
using AutoMapper;
using Data.DTOs;
using Data.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Modules.CityModule;
using Modules.PhoneModule;
using Modules.SpecializationModule;
using Modules.SubjectModule;
using Modules.TutorModule;
using System.Threading.Tasks;
using TutorsOfMogilev_NetCore.Models;
using TutorsOfMogilev_NetCore.Services;

namespace TutorsOfMogilev_NetCore.Controllers.MVC
{
    public class ResumeController : Controller
    {
        private readonly TutorRepository _tutorRepo;
        private readonly CityRepository _cityRepo;
        private readonly SpecializationRepository _specializationRepo;
        private readonly SubjectRepository _subjectRepo;
        private readonly PhoneRepository _phoneRepo;
        private readonly IMapper _mapper;
        private readonly ImageService _imageService;

        public ResumeController(
            TutorRepository tutorRepository,
            CityRepository cityRepository,
            SpecializationRepository specializationRepository,
            SubjectRepository subjectRepository,
            PhoneRepository phoneRepository,
            IMapper mapper,
            ImageService imageService
            )
        {
            _tutorRepo = tutorRepository;
            _cityRepo = cityRepository;
            _specializationRepo = specializationRepository;
            _subjectRepo = subjectRepository;
            _phoneRepo = phoneRepository;
            _mapper = mapper;
            _imageService = imageService;
        }

        public async Task<IActionResult> Add()
        {
            ViewBag.Cities = new SelectList(await _cityRepo.GetList(), "Id", "Name");
            ViewBag.Specializations = new MultiSelectList(await _specializationRepo.GetList(), "Id", "Name");
            ViewBag.Subjects = new MultiSelectList(await _subjectRepo.GetList(), "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([FromForm] ResumeVM resume)
        {
            if (ModelState.IsValid)
            {
                var tutorDTO = _mapper.Map<TutorDTO>(resume);
                tutorDTO.City = await _cityRepo.GetItem(resume.CityId);

                var newTutor = await _tutorRepo.InsertItem(tutorDTO);
                await _tutorRepo.UpdateTutorSpecializations(newTutor.Id, resume.SpecializationsIds, new long[] { });
                await _tutorRepo.UpdateTutorSubjects(newTutor.Id, resume.SubjectsIds, new long[] { });
                await _phoneRepo.InsertItem(new Phone
                {
                    TutorId = newTutor.Id,
                    Number = resume.Phone,
                    Operator = resume.PhoneOperator
                });

                var IsPhotoLoadSuccess = await LoadPhoto(resume.Photo, newTutor.Id);

                if (!IsPhotoLoadSuccess)
                    ModelState.AddModelError("", "Ошибка при загрузке фото");
                else
                    return RedirectToAction("Success");
            }

            ViewBag.Cities = new SelectList(await _cityRepo.GetList(), "Id", "Name");
            ViewBag.Specializations = new MultiSelectList(await _specializationRepo.GetList(), "Id", "Name");
            ViewBag.Subjects = new MultiSelectList(await _subjectRepo.GetList(), "Id", "Name");

            return View(resume);
        }

        public IActionResult Success()
        {
            return View();
        }

        private async Task<bool> LoadPhoto(IFormFile photo, long tutorId)
        {
            if (photo != null && _imageService.IsImage(photo))
            {
                var tutor = await _tutorRepo.GetItem(tutorId);
                var oldPhoto = tutor.PhotoPath;

                if (!string.IsNullOrWhiteSpace(oldPhoto))
                {
                    _imageService.DeleteOldPhoto(oldPhoto);
                }

                var savedPhotoName = _imageService.SavePhoto(photo.OpenReadStream());

                await _tutorRepo.SetPhotoPath(tutorId, savedPhotoName);

                return true;
            }

            return false;
        }
    }
}

TutorsOfMogilev_NetCore/Views/Resume/Add.cshtml
@model ResumeVM

@{
    ViewBag.Title = "Оставить заявку";
    ViewBag.MenuActive = "Оставить заявку";
}

@section Styles
    {
    <link rel="stylesheet" href="~/styles/resume.css" />
}

<div class="text-danger" asp-validation-summary="ModelOnly"></div>

<div class="resume">
    <form asp-controller="Resume" asp-action="Add" asp-antiforgery="true" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label required" asp-for="FirstName"></label>
                <input class="form-control" type="text" asp-for="FirstName" />
                <span class="text-danger" asp-validation-for="FirstName" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label required" asp-for="LastName"></label>
                <input class="form-control" type="text" asp-for="LastName" />
                <span class="text-danger" asp-validation-for="LastName" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label required" asp-for="Patronymic"></label>
                <input class="form-control" type="text" asp-for="Patronymic" />
                <span class="text-danger" asp-validation-for="Patronymic" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label required" asp-for="CityId"></label>
                <select class="form-control"
                        asp-for="CityId"
                        asp-items="ViewBag.Cities"></select>
                <span class="text-danger" asp-validation-for="CityId" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" asp-for="SpecializationsIds"></label>
                <select class="form-control"
                        multiple
                        title="Выберите специализации"
                        asp-for="SpecializationsIds"
                        asp-items="ViewBag.Specializations"></select>
                <span class="text-danger" asp-validation-for="SpecializationsIds" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label required" asp-for="SubjectsIds"></label>
                <select class="form-control"
                        multiple
                        title="Выберите предметы"
                        asp-for="SubjectsIds"
                        asp-items="ViewBag.Subjects"></select>
                <span class="text-danger" asp-validation-for="SubjectsIds" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label required" asp-for="Education"></label>
                <textarea class="form-control resume-large-textarea" asp-for="Education"></textarea>
                <span class="text-danger" asp-validation-for="Education" />
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label required" asp-for="Experience"></label>
                        <input class="form-control" type="number" placeholder="Полных лет" asp-for="Experience" />
                        <span class="text-danger" asp-validation-for="Experience" />
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label required" asp-for="Cost"></label>
                        <input class="form-control" type="number" step="0.01" placeholder="BYN" asp-for="Cost" />
                        <span class="text-danger" asp-validation-for="Cost" />
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label required" asp-for="Phone"></label>
                        <input class="form-control" type="text" asp-for="Phone" />
                        <span class="text-danger" asp-validation-for="Phone" />
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="PhoneOperator"></label>
                        <input class="form-control" type="text" placeholder="МТС, Velcom..." asp-for="PhoneOperator" />
                        <span class="text-danger" asp-validation-for="PhoneOperator" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label" asp-for="Address"></label>
                <textarea class="form-control" asp-for="Address"></textarea>
                <span class="text-danger" asp-validation-for="Address" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" asp-for="Description"></label>
                <textarea class="form-control" placeholder="Пару слов о себе" asp-for="Description"></textarea>
                <span class="text-danger" asp-validation-for="Description" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" asp-for="Job"></label>
                <textarea class="form-control" asp-for="Job"></textarea>
                <span class="text-danger" asp-validation-for="Job" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                Фото: <input type="file" asp-for="Photo" />
            </div>
        </div>

        <div class="resume-active-btn-container">
            <div class="resume-active-btn-group">
                <input class="btn btn-info" type="submit" value="Сохранить" />
                <a class="btn btn-danger" asp-controller="Resume" asp-action="Add">
                    Отмена
                </a>
            </div>
        </div>
    </form>
</div>

@section Scripts
    {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TutorsOfMogilev_NetCore/Views/Resume/Success.cshtml
@{
    ViewData["Title"] = "Success";
    ViewBag.MenuActive = "Оставить заявку";
}

@section Styles
    {
    <link rel="stylesheet" href="~/styles/resume.css" />
}

<h2 class="text-success">Ваша заявка принята, она будет рассмотрена нашими администраторами.</h2>

<div><a asp-action="List" asp-controller="Tutors">Вернуться на главную</a></div>